refactor: move commands

diff --git a/packages/starter/plopfiles/plugins/husky/.husky/pre-commit b/packages/starter/plopfiles/plugins/husky/.husky/pre-commit
--- a/packages/starter/plopfiles/plugins/husky/.husky/pre-commit
+++ b/packages/starter/plopfiles/plugins/husky/.husky/pre-commit
@@ -1,2 +1,9 @@
+branch="$(git rev-parse --abbrev-ref HEAD)"
+
+if [ "$branch" = "main" ]; then
+  echo "👮‍ You can't commit directly to $branch branch"
+  exit 1
+fi
+
 rr test:static --fix-staged
 git update-index --again
